# Node test setup 
cluster.name: test.cluster
name: test.node

# Disable network 
discovery.zen.ping.multicast.enabled: false
node.local: true

# Using less filesystem as possible 
index.store.type: memory
index.store.fs.memory.enabled: true
index.gateway.type: none
gateway.type: none

# scripting
es.script.disable_dynamic: false
script.groovy.sandbox.enabled: true
